### ISSUE TITLE
Using txmemchache with membase

### ISSUE THREAD

**Issue by SSPkrolik** [dpnova/txmemcache#1]
As far as I know membase db uses memcache protocol for communication and similar to memcache architecture. Is it possible to use txmemcache for working with membase without any or with minor modifications?

**Comment by dpnova** [comment]
Hey, sorry about the late reply on this, I never got an email notification.

I'm not sure is the answer to that... sorry!

I haven't been using this lib much lately.. so I haven't been keeping up with that's going on..
